- virt_net:
    command: facts

- set_fact:
    dn: "{{ ansible_libvirt_networks[default_network] | default ('undefined') }}"

- name: define new network
  virt_net:
    name: "{{ default_network }}"
    command: "define"
    xml: '{{ lookup("template", "default_network.xml.j2") }}'
  when: dn is not defined or dn == "undefined"

- virt_net:
    command: facts

- set_fact:
    dn: "{{ ansible_libvirt_networks[default_network] }}"

- virt_net:
    command: create
    name: "{{ default_network }}"
  when: dn.state != "active"

- virt_net:
    autostart: yes
    name: "{{ default_network }}"
