- name: ensure config.yml
  template:
    src: config.yml.j2
    dest: "{{ vm_create_libvirt_images_path }}/{{ vm_create_config_yml }}"
    mode: 0777

- name: make config.iso
  command: "cloud-localds {{ vm_create_config_iso }} {{ vm_create_config_yml }}"
  args:
    chdir: "{{ vm_create_libvirt_images_path }}"

