- name: ensure image path exists
  file:
    path: "{{ vm_create_libvirt_images_path }}"
    state: directory
    recurse: yes

- name: ensure boot path exists
  file:
    path: "{{ vm_create_libvirt_images_boot }}"
    state: directory
    recurse: yes
