---
- name: List all VMs
  virt:
    command: info
  register: all_vms

- set_fact:
    vm: "{{ all_vms[vm_create_name] | default ('undefined') }}"

- name: Ensure VM if not defined
  import_tasks: ensure_vm.yml
  when: vm is not defined or vm == "undefined"
