---
- name: Update
  apt:
    update_cache: yes
  tags: ["ensure_system", "system_update"]

- name: Install required packages
  apt:
    name:
      - "ubuntu-vm-builder"
      - "qemu-kvm"
      - "libvirt-bin"
      - "ubuntu-vm-builder"
      - "bridge-utils"
      - "virtinst"
      - "libvirt-dev"
      - "libvirt-bin"
      - "cloud-image-utils"
      - "python-pip"
      - "python3-pip"
  tags: ["ensure_system", "system_install_packages"]

- name: Install required pip packages
  pip:
    name:
      - "lxml"
      - "libvirt-python"
  tags: ["ensure_system", "system_install_pip_packages"]
