---
- name: Update
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - "ubuntu-vm-builder"
      - "qemu-kvm"
      - "libvirt-bin"
      - "bridge-utils"
      - "virtinst"
      - "libvirt-dev"
      - "libvirt-bin"
      - "cloud-image-utils"
      - "python-pip"
      - "python3-pip"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int == 18

- name: Install required packages
  apt:
    name:
      - "qemu-kvm"
      - "libvirt-clients"
      - "libvirt-daemon-system"
      - "cloud-image-utils"
      - "python-pip"
      - "python3-pip"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int > 18

- name: Install required pip packages
  pip:
    name:
      - "lxml"
      - "libvirt-python"
