- name: destroy VM
  virt:
    name: "{{ vm_name }}"
    command: "destroy"

- name: undefine VM
  virt:
    name: "{{ vm_name }}"
    command: "undefine"

- name: clean config.yml
  file:
    path: "{{ libvirt_images_path }}/{{ vm_config_yml }}"
    state: absent

- name: clean config.iso
  file:
    path: "{{ libvirt_images_path }}/{{ vm_config_iso }}"
    state: absent

- name: clean image
  file:
    path: "{{ libvirt_images_path }}/{{ libvirt_image_name }}"
    state: absent

#- name: Deallocate IP address
#  command: "/usr/bin/virsh net-update {{ libvirt_network }} delete ip-dhcp-host \"<host mac='{{ vm_mac }}' ip='{{ vm_ip }}'/>\" --config --live --parent-index 0 "
