- name: check if image downloaded
  stat:
    path: {{ libvirt_images_boot }}/{{ libvirt_image_distibution }}
    register: image_downloaded

- name: download image
  get_url:
    url: "{{ libvirt_image_url }}"
    dest: "{{ libvirt_images_boot }}/{{ libvirt_image_distibution }}"
    mode: '0777'
  when: not image_downloaded.stat.exists
