---
- name: List all VMs
  virt:
    command: info
  register: all_vms
  tags: ["ensure_vm", "destroy_vm"]

- set_fact:
    vm: "{{ all_vms[vm_name] | default ('undefined') }}"
  tags: ["ensure_vm", "destroy_vm"]

- name: Start VM if defined
  virt:
    name: "{{ vm_name }}"
    state: running
  when: vm is defined and vm != "undefined" and vm.state != "running"
  tags: ["ensure_vm"]

- name: Ensure VM if not defined
  import_tasks: ensure_vm.yml
  when: vm is not defined or vm == "undefined"
  tags: ["ensure_vm"]

- name: destroy VM if defined
  import_tasks: destroy.yml
  when: vm is defined and vm != "undefined"
  tags: ["destroy_vm"]
