---
- name: List all VMs
  virt:
    command: info
  register: all_vms

- set_fact:
    vm: "{{ all_vms[vm_destroy_name] | default ('undefined') }}"

- name: Destroy VM
  virt:
    name: "{{ vm_destroy_name }}"
    command: "destroy"
  when: vm is defined and vm != "undefined" and vm.state == "running"

- name: Destroy VM if defined
  import_tasks: destroy.yml
  when: vm is defined and vm != "undefined"
