- name: Make lvm disk
  command: "qemu-img create -f raw {{ vm_lvm_create_libvirt_images_path }}/{{ vm_lvm_create_disk_name }} {{ vm_lvm_create_disk_size }}"

- name: Attach lvm disk
  command: "virsh attach-disk {{ vm_lvm_create_name }} --source {{ vm_lvm_create_libvirt_images_path }}/{{ vm_lvm_create_disk_name }} --target vdb --persistent"
  ignore_errors: yes
